version: "3.7"

services:
  producer_1:
    build: ../producer
    environment:
      PRODUCER_ID: 1
      KAFKA_BROKER_URL: kafka-1:29092
      DETECTIONS_TOPIC: epic.detections
      DETECTIONS_PER_SECOND: 1
    networks:
      - mynet

  producer_2:
    build: ../producer
    environment:
      PRODUCER_ID: 2
      KAFKA_BROKER_URL: kafka-1:29092
      DETECTIONS_TOPIC: epic.detections
      DETECTIONS_PER_SECOND: 2
    networks:
      - mynet

networks:
  mynet:
