version: '1.0'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./config:/mosquitto/config
      - ./passwd:/mosquitto/passwd
    restart: unless-stopped
    networks:
      - mynet

volumes:
  mosquitto_data:
  mosquitto_log:

networks:
  mynet:

