version: "3.7"

services:
  couchdb:
    image: couchdb:latest  
    container_name: couchdb
    volumes:
      - couchdb_data:/opt/couchdb/data
    environment:
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
    ports:
      - "127.0.0.1:5984:5984"
    networks:
      - mynet
    mem_limit: 256m
    cpus: 0.5

volumes:
  couchdb_data:

networks:
  mynet:
